config/routes.rb
Requester::Application.routes.draw do
  
  
  devise_for :users, :path => 'auth'
  resources :users
  
  match 'events/pending(/:site)' => 'events#pending', :as => 'pending_events', :via => :get
  match 'events/approved(/:site)' => 'events#approved', :as => 'approved_events', :via => :get
  match 'events/denied(/:site)' => 'events#denied', :as => 'denied_events', :via => :get
  
  resources :events do
    member do
      get 'confirm'
      put 'approve'
      get 'edit_denial', :as => 'edit_denial_for'
      put 'deny'
    end
  end
  
  root :to => "events#new"

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :site
  has_and_belongs_to_many :needs
  
  validates_presence_of :start_time, :end_time, :site
    
  before_save :set_endtime_date_to_starttime_date
  
  # TODO attr_accessible protect state
  
  #attr_accessor :start_hour, :start_minute, :end_hour, :end_minute
  
  state_machine :state, :initial => :pending do
    event :approve do
      transition all => :approved
    end
    
    event :deny do
      transition all => :denied
    end
  end
  
  # scope by site, accepts int or array
  def self.by_site(site)
    where(:site_id => site).order('site_id').includes(:needs)
  end
  
  def self.pending
    where(:state => 'pending')
  end
  
  def self.approved
    where(:state => 'approved')
  end
  
  def self.denied
    where(:state => 'denied')
  end
  
  def fdate
    start_time.strftime("%b %e %Y") unless start_time.nil?
  end
  
  def fstart
    start_time.strftime("%l:%M %p") unless start_time.nil?
  end
  
  def fend
    end_time.strftime("%l:%M %p") unless end_time.nil?
  end
  
  private
  
  def set_endtime_date_to_starttime_date
    s = self.start_time.in_time_zone(Time.zone)
    e = self.end_time.in_time_zone(Time.zone)
    self.end_time = DateTime.new(s.year, s.month, s.day, e.hour, e.min, e.sec, s.zone)
  end
  
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_filter :authenticate_user!, :except => ['new', 'create', 'confirm']
  
  # GET /events
  # GET /events.json
  def index
    # @events = Event.order('created_at desc').limit(15)
    @events = Event.by_site( current_user.sites )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
  
  def pending
    @events = Event.by_site( current_user.sites ).pending
  end
  
  def approved
    @events = Event.by_site( current_user.sites ).approved
  end
  
  def denied
    @events = Event.by_site( current_user.sites ).denied
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end
  
  # GET /events/1/confirm
  # GET /events/1/confirm.json
  def confirm
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @needs = Need.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @needs = Need.all
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        EventMailer.confirmation_email(@event).deliver
        if @event.site.users.any?
          EventMailer.approval_notice(@event).deliver
        end
        if @event.needs.any?
          EventMailer.staff_notice(@event).deliver
        end
        
        format.html { redirect_to '/thank_you.html', notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
  
  def approve
    @event = Event.find(params[:id])
    if @event.approve
      EventMailer.approved_notice(@event).deliver
      redirect_to events_path, notice: 'Event approved.'
    else
      render action: "index", notice: 'There was a problem approving that event.'
    end
  end
  
  def edit_denial
    @event = Event.find(params[:id])
  end
  
  def deny
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      if @event.deny
        EventMailer.denied_notice(@event).deliver
        redirect_to events_path, notice: 'Event denied.'
      else
        render action: "edit_denial"
      end
    else
      render action: "edit_denial"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def startoptions
    {
      :ampm => true, 
      :start_year => 2011, 
      :end_year => 2012,
      :order => [:month,:day,:year]
    }
  end
  
  def endoptions
    {
      :ampm => true, 
      :discard_year => true, 
      :discard_month => true,
      :start_year => 2011, 
      :end_year => 2012
    }
  end
  
  def configured_select_hour(initial, field_pre)
    options = {
      :ampm => true, 
      :prefix => "event",
      :field_name => "#{field_pre}_time(4i)",
      :start_hour => 7,
      :end_hour => 20
    }
    select_hour initial, options
    
  end
  
  def configured_select_minute(initial, field_pre)
    select_minute Time.now, :prefix => "event", :minute_step => 15, :field_name => "#{field_pre}_time(5i)"
  end
  
  def listed_areas(event)
    unless event.area.nil?
      multi = event.area.split(',')
    
      if multi.length > 1
        output = "<ul>"
        multi.each do |a|
          output << "<li>"
          output << a.html_safe # => Does this filter like you think it does?
          output << "</li>"
        end
        output << "</ul>"
      else
        output = event.area
      end
    
      raw output
    end
  end
  
  def is_active?(action)
    "active" if current_page?(:action => action)
  end
  
  def active_page?(opts)
    "active" if current_page?(opts)
  end
  
end

module ActionView
  module Helpers
    class DateTimeSelector
      
      def select_hour
        if @options[:use_hidden] || @options[:discard_hour]
          build_hidden(:hour, hour)
        else
          # start_hour = @options[:start_hour] || 0
          # end_hour = @options[:end_hour] || 23
          
          build_options_and_select(:hour, hour, { :end => @options[:end_hour], :start => @options[:start_hour], :ampm => @options[:ampm] } )
        end
      end
      
    end
  end
end

app/views/events/_event.html.erb
<div class="event group">
  <a href="#" class="drawer_toggle">
    <div class="event_title group">
      <div class="twirl"></div>
      <hgroup>
        <h2><%= event.title.titlecase %></h2>
        <h4><%= event.site.name.titlecase unless event.site.nil? %></h4>
      </hgroup>
      <div class="date_time">
        <h5 class="date"><%= event.start_time.strftime("%b %e") unless event.start_time.nil? %></h5>
        <p class="times"> 
        <span class="start"><%= event.start_time.strftime("%l:%M%p").downcase.chop %></span>
        <span class="separator">&ndash;</span>
        <span class="end"><%= event.end_time.strftime("%l:%M%p").downcase.chop %></span>
        </p>
      </div>
      <div class="state<%= " #{event.state}"%>"><span><%= event.state.capitalize %></span></div>
    </div>
  </a>
  

  <div class="event_drawer">
    <div class="drawer_top">
      <% unless event.area.nil? %>
      <div class="areas">
        <strong><%= event.area.split(',').count > 1 ? "Areas" : "Area" %></strong>
        <%= event.area %>
      </div>
      <% end %>
    
      <div class="needs">
        <strong>Needs</strong>
        <% if event.needs.any? %>
          <%= event.needs.collect(&:name).join(', ') %>
        <% else %>
          No needs requested.
        <% end %>
      </div>
    
      
      <div class="notes">
        <strong>Notes</strong>
        <div class="body">
          <% if event.note.nil? %>
            No notes given
          <% else %>
            <%= simple_format(event.note)%>
          <% end %>
        </div>
      </div>
      
    </div>
    <div class="drawer_bottom">
      
      <% unless event.requester.nil? %>
      <div class="requester">
        <%= link_to event.requester, "mailto:#{event.requester_email}" %>
      </div>
      <% end %>
      <div class="edit_event">
        <%= link_to 'Edit', edit_event_path(event) %>
      </div>
      <div class="event_state_actions">
        <div class="deny_event button">
          <%= link_to 'Deny', edit_denial_for_event_path(event) %>
        </div>
        <div class="approve_event button">
          <%= link_to 'Approve', approve_event_path(event), :method => :put %>
        </div>
      </div>
    </div><!-- /.event_bottom -->
    
  </div><!-- /.event_drawer -->
  
</div><!-- /.event -->

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset id="contact_info">
    <h3>How can we contact you?</h3>
    <div class="field" id="name">
      <%= f.label :requester, "Name" %><br />
      <%= f.text_field :requester %>
    </div>
    <div class="field" id="email">
      <%= f.label :requester_email, "Email" %><br />
      <%= f.text_field :requester_email %>
    </div>
  </fieldset>
  
  <fieldset id="event_info">
    <h3>What are the details for your event?</h3>
    <div class="field" id="event_desc">
      <%= f.label :title, "Event Description / Title" %><br />
      <%= f.text_field :title %>
    </div>
    
    <div class="field" id="event_site">
      <%= f.label :site_id %><br />
      <%= f.collection_select :site_id, Site.all, :id, :name %>
    </div>
    
    <div id="datetime_info">
      <div class="field" id="date">
        <% # find startoptions in events_helper %>
        <%= f.label :start_time, "Date" %><br />
        <%= f.date_select :start_time, startoptions %>
      </div>
      <div class="field" id="time_start">
        <%= label_tag "Start time" %>
        <%= configured_select_hour(Time.now, "start") %> :
        <%= configured_select_minute(Time.now, "start") %>
      </div>
    
      <div class="field" id="time_end">
        <%= label_tag "End time" %>
        <%= f.date_select :end_time, :discard_year => true, :discard_month => true, :discard_day => true %>
        <%= configured_select_hour(Time.now + 1.hour, "end") %> :
        <%= configured_select_minute(Time.now, "end") %>
      </div>
    </div>
    
    <div class="field">
      <%= f.label :area, "Area(s)" %><br>
      <%= f.text_field :area %>
      <div class="desc">Separate areas with commas <em>eg. "MPR, Room 15, Playground"</em></div>
    </div>
    
    <div class="field">
      <%= label :need_ids, "Event Needs" %>
  		<ul id="event_needs" class="group">
  			<% for need in @needs %>
  			<li>
  			  <label for="<%= need.name %>">
  				<%= check_box_tag "event[need_ids][]", need.id, @event.needs.include?(need), :id => need.name %>
  				<%= need.name %>
  				</label>
  			</li>
  			<% end %>
  		</ul>
  	</div>
  	
  	<div class="field">
  	 <%= f.label :note %>
  	 <%= f.text_area :note, :rows => 10 %>
  	</div>
  	
  </fieldset>
  
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/events/_state_nav.html.erb
<ul class="horz menu">
  <li><%= link_to "All", events_path, :class => active_page?(events_path) %></li>
  <li><%= link_to "Pending", pending_events_path, :class => active_page?(pending_events_path) %></li>
  <li><%= link_to "Approved", approved_events_path, :class => active_page?(approved_events_path) %></li>
  <li><%= link_to "Denied", denied_events_path, :class => active_page?(denied_events_path) %></li>
</ul>

app/views/events/approved.html.erb
<div id="title">
  <h1>Approved Events</h1>
  <%= render :partial => 'state_nav' %>
</div>

<div id="events">
  <%= render @events %>
</div>

app/views/events/confirm.html.erb
<div id="content">
<h1>Your request was received.</h1>
<p><em>We will be in touch.</em></p>

<p>
  <b>Requester:</b>
  <%= @event.requester %>
</p>

<p>
  <b>Requester email:</b>
  <%= @event.requester_email %>
</p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Start time:</b>
  <%= @event.fstart %>
</p>

<p>
  <b>End time:</b>
  <%= @event.fend %>
</p>

<p>
  <b>Site:</b>
  <%= @event.site.name %>
</p>

<p>
  <b>Area:</b>
  <%= @event.area %>
</p>

<p>
  <b>Needs:</b>
  <ul>
    <% @event.needs.each do |need| %>
    <li><%= need.name %></li>
    <% end %>
  </ul>
</p>

<p>
  <b>State:</b>
  <%= @event.state %>
</p></div>

app/views/events/denied.html.erb
<div id="title">
  <h1>Denied Events</h1>
  <%= render :partial => 'state_nav' %>
</div>
  
<div id="events">
  <%= render @events %>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>
<div id="content">
  <div class="border"></div>
  <%= render 'form' %>
</div>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/edit_denial.html.erb
<div id="content">
  <%= form_for @event, :url => deny_event_path, :method => :put do |f| %>
  
  <fieldset id="event_denial">
    <p><%= f.label :denial_message_text, "Denial Message"%></p>
    <div><%= f.text_area :denial_message_text %></div>
  </fieldset>
  
  <div class="actions">
    <%= link_to 'Cancel', events_path %>
    <%= f.submit "Submit" %>
  </div>
  
  <% end %>
</div>

app/views/events/index.html.erb
<div id="title">
  <h1>All Events</h1>
  <%= render :partial => 'state_nav' %>
</div>


  <div id="events">
    <%= render @events %>
  </div>

app/views/events/new.html.erb
<div id="title">
  <h1>New Event Request</h1>
</div>

<div class="border"></div>
<div id="content">
  <%= render 'form' %>
</div>

app/views/events/pending.html.erb
<div id="title">
  <h1>Pending Events</h1>
  <%= render :partial => 'state_nav' %>
</div>

<div id="events">
  <%= render @events %>
</div>

app/views/events/show.html.erb
<div id="content">

<p>
  <b>Requester:</b>
  <%= @event.requester %>
</p>

<p>
  <b>Requester email:</b>
  <%= @event.requester_email %>
</p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Start time:</b>
  <%= @event.fstart %>
</p>

<p>
  <b>End time:</b>
  <%= @event.fend %>
</p>

<p>
  <b>Site:</b>
  <%= @event.site.name %>
</p>

<p>
  <b>Area:</b>
  <%= @event.area %>
</p>

<p>
  <b>Needs:</b>
  <ul>
    <% @event.needs.each do |need| %>
    <li><%= need.name %></li>
    <% end %>
  </ul>
</p>

<p>
  <b>State:</b>
  <%= @event.state %>
</p>
</div>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>