config/routes.rb
Requester::Application.routes.draw do
  
  
  devise_for :users, :path => 'auth'
  resources :users
  
  match 'events/pending(/:site)' => 'events#pending', :as => 'pending_events', :via => :get
  match 'events/approved(/:site)' => 'events#approved', :as => 'approved_events', :via => :get
  match 'events/denied(/:site)' => 'events#denied', :as => 'denied_events', :via => :get
  
  resources :events do
    member do
      get 'confirm'
      put 'approve'
      get 'edit_denial', :as => 'edit_denial_for'
      put 'deny'
    end
  end
  
  root :to => "events#new"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Requester</title>
  
  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="user-scalable=no,width=device-width,initial-scale=1.0">
  
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="rh">
    <% if user_signed_in? %>
    <header class="group">
      <h1>SUSD Event Requests</h1>
      
      <div id="account">Signed in as <%= link_to current_user.email, edit_user_path(current_user) %> / <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></div>
      
      <nav class="group">
        <ul class="horz menu">
          <li><%= link_to "New Event", new_event_path %></li>
          <li><%= link_to "Manage Events", events_path %></li>
          <% if current_user.is_admin? %>
          <li><%= link_to "Manage Users", users_path %></li>
          <% end %>
        </ul>
      </nav>
      
    </header>
    <% end %>
    
    <div id="page">
      
      <% unless notice.nil? && alert.nil? %>
      <div id="messages">
        <% unless notice.nil? %>
        <div class="notice">
          <%= notice %>
        </div>
        <% end %>
        <% unless alert.nil? %>
        <div class="alert">
          <%= alert %>
        </div>
        <% end %>
      </div>
      <% end %>
      
      
      <%= yield %>
      
      <footer>
        <% unless user_signed_in? || current_page?(new_user_session_path) %>
        <p><%= link_to "Sign in", new_user_session_path %></p>
        <% end %>
      </footer>
      
    </div>
  </div>
</body>

</html>